// <auto-generated />
namespace Fitness_Asp.Net_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TableAddedAdminUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableAddedAdminUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201907091614401_Table Added AdminUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
